baseURL   = "https://mmontielpz.github.io/miguel.lopez.ai/"
languageCode = "en-us"
title     = "Miguel López"
theme     = "PaperMod"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home     = ["HTML","RSS","JSON"]
  section  = ["HTML"]
  page     = ["HTML"]
  taxonomy = ["RSS"]
  term     = ["HTML"]
